### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by huntingphi** [take-on/prep#2]
We need a concept!

**Comment by huntingphi** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>
<body>
    <div class = "container">
        <h1>Rake it up</h1>
        <div>
            <h2>Mission Objective</h2>
            <p>
                Rake it up aims to rake up new and talented grads.
                It provides a way for graduates to show off their skills and also familiarise themselves with oppertunities at investec.
            </p>
        </div>
        <div id = features>
            <h2>Features</h2>
            <ul>
                <li>Stay up to date with new company oppertunities and events</li>
                <li>Create a profile for graduates and company employees</li>
                <li>See a roadmap of your potential paths at various companies</li>
                <li>Earn brownie points by participating in company events and building your profile</li>
                <li>View current in demand skills</li>
                <li>24/7 Chatbot support</li>
            </ul>
        </div>
    </div>
    </body>
</html>

**Comment by huntingphi** [comment]
@takundac @Sbonelo-Challis @NYNALA001 @daniel-t-mabaso What do you guys think? Any other functionality to add? Should I be more descriptive?

**Comment by daniel-t-mabaso** [comment]
It's okay like this.

I think the features are sufficient. Let's just execute and deliver.

Rake it up... lol that, right there, is a funny name.

**Comment by NYNALA001** [comment]
I think it’s spot on.
